### ISSUE TITLE
Charts are being duplicated

### ISSUE THREAD

**Issue by Oleksii14** [apexcharts/vue3-apexcharts#3] opened 2020-11-30 09:27 UTC
Env:

```
"apexcharts": "^3.22.2",
"vue": "^3.0.2",
"vue3-apexcharts": "^1.1.1"
```

My options:

```
{
 chart: {
        height: 590,
        type: "area",
      },
      dataLabels: {
        enabled: false,
      },
      stroke: {
        curve: "smooth",
      },
      xaxis: {
        labels: {
          showDuplicates: false,
          hideOverlappingLabels: true,
          offsetY: 20,
          style: {
            colors: "#979797",
          },
        },
      },
}
```

Template:

```
<apexchart type="area" :height="590" :options="options" :series="series" />
```

Result: 

![image](https://user-images.githubusercontent.com/36737084/100591839-fea15500-32fe-11eb-9935-5ef17c248c02.png)

Note: when I change a screen resolution, the duplicated one disappears

**Comment by junedchhipa** [comment] 2020-12-15 16:07
Sorry for the late response.
Can you please create a Codesandbox demo to reproduce this?

**Comment by oleksii-shaposhnikov** [comment] 2020-12-15 16:35
> Sorry for the late response.
> Can you please create a Codesandbox demo to reproduce this?

I have fixed this issue by using `apexcharts` package without vue wrapper. I will attach demo link ASAP

**Comment by lucasdcrk** [comment] 2021-05-05 18:50
Same issue here using the latest versions of Vue, VueApexCharts and ApexCharts 
I created a Codesandbox here: https://codesandbox.io/s/cool-jennings-qbbr5?file=/src/App.vue

**Comment by mijreed** [comment] 2021-05-08 03:56
Having the same issue. Any resolution to it?

**Comment by Oleksii14** [comment] 2021-05-08 10:54
@mijreed just use a vanilla js package without a Vue wrapper. It may be a temporary solution

**Comment by oleksii-shaposhnikov** [comment] 2021-05-08 11:08
@mijreed you can use it like

```
<template>
  <div id="chart" />
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import ApexChart from "apexcharts";

export default defineComponent({
  setup() {
    let chartInstance;

    const options = {
      colors: ["#1890FF", "#FA4F60"],
      chart: {
        type: "area",
      },
      stroke: {
        curve: "smooth",
      },
    };

    const getChartData = () => [
      {
        name: "Test",
        data: [
          {
            x: "1",
            y: 2,
          },

          {
            x: "2",
            y: 2,
          },
        ],
      },
    ];

    onMounted(() => {
      chartInstance = new ApexChart(document.querySelector("#chart"), {
        ...options,
        series: getChartData(),
      });
      chartInstance.render();
    });
  },
});
</script>
```

**Comment by Oleksii14** [comment] 2021-05-08 11:12
@mijreed you can use it like

```
<template>
  <div id="chart" />
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import ApexChart from "apexcharts";

export default defineComponent({
  setup() {
    let chartInstance;

    const options = {
      colors: ["#1890FF", "#FA4F60"],
      chart: {
        type: "area",
      },
      stroke: {
        curve: "smooth",
      },
    };

    const getChartData = () => [
      {
        name: "Test",
        data: [
          {
            x: "1",
            y: 2,
          },

          {
            x: "2",
            y: 2,
          },
        ],
      },
    ];

    onMounted(() => {
      chartInstance = new ApexChart(document.querySelector("#chart"), {
        ...options,
        series: getChartData(),
      });
      chartInstance.render();
    });
  },
});
</script>
```

**Comment by kalenpw** [comment] 2021-07-09 00:28
I can confirm, it is a problem with Vue3 using Vite as well.  Same issue where if a resize happens the duplicate disappears.

**Comment by NWBY** [comment] 2021-07-21 16:50
Having this issue too. Opening the development tools or resizing the window causes the duplicate to disappear.

**Comment by 0x62** [comment] 2021-08-06 14:40
+1 also having this issue with Vue 3 and Vite

**Comment by lukesnowden** [comment] 2021-08-13 07:57
```
mounted() {
    this.$nextTick(() => {
        window.dispatchEvent(new Event('resize'));
    });
}
```

Will fix the issue for now

**Comment by horia161999** [comment] 2021-08-25 08:40
Having the same issue.

**Comment by IvanBalakirev** [comment] 2021-10-30 10:48
The same here!

**Comment by elreco** [comment] 2021-11-08 17:16
same issue :/

**Comment by haroon97** [comment] 2021-11-24 14:22
Facing the exactly same issue

**Comment by andreashe** [comment] 2021-12-12 18:22
Me too!

**Comment by mjwweb** [comment] 2022-01-23 20:37
Still not fixed

**Comment by Flloooow** [comment] 2022-01-26 09:30
You just need to change mounted() to created(), resolving the issue for me

**Comment by mperrien** [comment] 2022-06-24 15:26
And if you're using the Composition API (ie `<script setup>` syntax) use `onBeforeMount` instead of `onMounted`.

**Comment by gorillaworkout** [comment] 2022-07-18 08:56
> And if you're using the Composition API (ie `<script setup>` syntax) use `onBeforeMount` instead of `onMounted`.


its worked well. awesome

**Comment by razorness** [comment] 2022-07-19 13:14
This happens because you mount the component and use reactivity too quickly before the apex component can be initialized. In this case, the `init` method of the component will be triggered twice, becaus it is waiting for the _next tick_ to continue. 
So, instead of arguing with _triggering the resize event_ and having duplicates for a short time, you should wrap your data binding in a call of `nextTick`.

This is my work around as long as #50  is not accepted, which adds an additional check within the `init` method.

**Closed** 2022-10-15 11:20 UTC

**Comment by acidjazz** [comment] 2022-10-17 20:13
May I ask why this is closed? I had to implement the nextTick workaround I found via https://stackoverflow.com/a/70826352/2817604 - looks like it was picked from https://github.com/apexcharts/vue3-apexcharts/issues/3#issuecomment-898265002

**Comment by razorness** [comment] 2022-10-17 20:19
Which version are you using?

**Comment by acidjazz** [comment] 2022-10-17 20:22
```    "vue3-apexcharts": "^1.4.1",```


NuxtJS V3 project using a plugin:

```ts
import VueApexCharts from 'vue3-apexcharts'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueApexCharts)
})

```

**Comment by acidjazz** [comment] 2022-10-17 20:23
just saw your PR and the fix - nice work @razorness  - can we get a patch release? i'll update that SO question

**Comment by Jonorusc** [comment] 2022-11-08 15:39
> this.$nextTick(() => {
>         window.dispatchEvent(new Event('resize'));
>     });

thank you. It works for me

**Comment by jice-lavocat** [comment] 2022-11-12 18:44
> [...] I had to implement the nextTick workaround [...]

Until the patch is released, could you share how you implemented this in Nuxt3 @acidjazz ?
I'm struggling to do it properly.

**Comment by acidjazz** [comment] 2022-11-12 19:19
Nuxt V3:

`plugins/apex.client.ts`

```ts
import VueApexCharts from 'vue3-apexcharts'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueApexCharts)
})
```

`components/PublicChartLine.vue`

```html
<script lang="ts" setup>
import { ApexOptions } from 'apexcharts'

const options:ApexOptions = {
  colors: ['#6667ab', 'green'],
  tooltip: { theme: 'none' },
  chart: {
    type: 'line',
    toolbar: { show: false },
    foreColor: '#6b7280',
  },
  grid: { show: false },
  markers: {
    size: 6,
    colors: ['#6667ab'],
  },
  xaxis: {
    title: { text: 'Year' },
    tooltip: { enabled: false },
    categories: [2018, 2019, 2020, 2021, 2022],
    axisBorder: { show: false },
    axisTicks: { show: false },
  },
  yaxis: {
    title: { text: 'Days' },
  },
  stroke: {
    show: true,
    curve: 'smooth',
  },
  fill: {
    type: 'gradient',
    gradient: {
      type: 'horizontal',
      colorStops: [
        {
          offset: 1,
          color: '#9c9ae3',
          opacity: 1,
        },
        {
          offset: 100,
          color: '#00c893',
          opacity: 1,
        },
      ],
    },
  },
  dataLabels: {
    style: {
      colors: ['#6667ab'],
    },
  },
}
const series = [
  {
    name: 'Days',
    data: [352, 203, 126, 51, 8],
  },
]

onMounted(() => {
  nextTick(() => {
    window.dispatchEvent(new Event('resize'))
  })
})
</script>

<template>
  <div>
    <apexchart
      class="hidden lg:block w-470px" :options="options" :series="series"
      width="470"
    />
    <apexchart
      class="lg:hidden" :options="options" :series="series"
      width="370"
    />
  </div>
</template>
```

**Comment by jice-lavocat** [comment] 2022-11-12 22:19
Thanks, that works like a charm.
My code was pretty similar to your, but I tried to do the refresh at the `plugin` side and not at the `component` side. Something along the lines: 

`plugins/apex.client.ts` (not working)

```
import VueApexCharts from 'vue3-apexcharts'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueApexCharts)

  nuxtApp.hook('page:finish', (pageComponent) => {
    nextTick()
    window.dispatchEvent(new Event('resize'))
  })

})
```

But I couldn't find why this didn't work.

**Comment by thiagopetherson** [comment] 2023-02-22 14:59
I added a key to the graph and it worked.

`<apexchart type="area" :options="options" :series="series" :key="chart-items-`${series[0].data.length}`"></apexchart>`

**Comment by Josmun55** [comment] 2023-04-04 08:40
Window.dispatchEvent(new Event('resize')) on both onMounted and updated caused a visible flick of the duplicate before it got removed. Solved it by reassigning the data.

```
onMounted(() => {
      nextTick(() => {
        series.value = [...props.graphData];
      })
    })
```

**Comment by ravisharmaa** [comment] 2023-04-09 02:22
Also faced this same, and updating the data on `beforeMount` worked for me.

**Comment by emmanuelizzy** [comment] 2023-06-27 16:50
> I added a ":key" to the graph and it solved.
> 
> `<apexchart type="area" :options="options" :series="series" :key="chart-items-`${series[0].data.length}`"></apexchart>`

I love this solution better using `:key` which forces a component re-render and the best thing is that apex-charts retains its animation with this approach.

**Comment by ishaiavrahami** [comment] 2023-07-10 08:14
there is still flick when doing  ```window.dispatchEvent(new Event('resize'));```. Is there a better solution?

**Comment by razorness** [comment] 2023-07-15 12:13
New version issued just 2 days ago. This issue should not happen anymore. Your hot fixes should be safe to remove.
